theme: jekyll-theme-minimal
title: Geek Source
description: An online shopping experience providing a number of real-world challenges web developers will face daily as a professional web developer.
logo: https://github.com/wesdollar/geek-source/blob/master/assets/logo.png
